version: '3'
services:
  db:
    container_name: auth_postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresData:/var/lib/postgresql/data
    networks:
      authNetwork:
  
  rabbitmq:
    container_name: auth_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      authNetwork:
    restart: unless-stopped
    volumes:
      - rabbitmqData:/var/lib/rabbitmq

volumes:
  postgresData:
    driver: local
  rabbitmqData:
    driver: local

networks:
  authNetwork:
    driver: bridge